# Generated by Django 4.2.7 on 2024-01-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementTrainingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='auth_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='authenticationTable',
        ),
        migrations.DeleteModel(
            name='basicUserDetailsTable',
        ),
        migrations.DeleteModel(
            name='upcomingTrainingTable',
        ),
    ]
