# Generated by Django 4.2.7 on 2024-03-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementTrainingApp', '0003_basicuserdetailstable_upcomingtrainingtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_faculty',
            old_name='reg_no',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='auth_student',
            old_name='reg_no',
            new_name='username',
        ),
    ]
